create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role = 'admin'),
  user_input uuid not null default auth.uid(),
  time_input timestamptz not null default now(),
  user_edit uuid,
  time_edit timestamptz,
  is_active boolean not null default true
);

create table public.member_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type_code char(1) not null default '1' check (type_code between '0' and '9'),
  is_active boolean not null default true,
  user_input uuid not null default auth.uid(),
  time_input timestamptz not null default now(),
  user_edit uuid,
  time_edit timestamptz
);

create table public.members (
  id bigint generated by default as identity primary key,
  role text not null default 'member' check (role in ('member', 'admin')),
  member_type_id bigint not null references public.member_types(id),
  user_id varchar(10) not null unique check (user_id ~ '^[0-9]{10}$'),
  barcode_value text not null unique,
  name text not null,
  nik text,
  email text,
  phone text,
  photo_path text,
  status text not null default 'active' check (status in ('active', 'inactive', 'pending', 'expired', 'deleted')),
  user_input uuid not null default auth.uid(),
  time_input timestamptz not null default now(),
  user_edit uuid,
  time_edit timestamptz
);

create table public.member_field_definitions (
  id bigint generated by default as identity primary key,
  field_key text not null unique,
  label text not null,
  data_type text not null default 'text' check (data_type in ('text', 'number', 'date', 'boolean')),
  is_required boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  user_input uuid not null default auth.uid(),
  time_input timestamptz not null default now(),
  user_edit uuid,
  time_edit timestamptz
);

create table public.member_field_values (
  member_id bigint not null references public.members(id) on delete cascade,
  field_definition_id bigint not null references public.member_field_definitions(id) on delete cascade,
  value text,
  primary key (member_id, field_definition_id)
);

create table public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  location text,
  start_at timestamptz not null,
  end_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'upcoming', 'ongoing', 'completed', 'cancelled')),
  user_input uuid not null default auth.uid(),
  time_input timestamptz not null default now(),
  user_edit uuid,
  time_edit timestamptz
);

create table public.event_member_types (
  event_id bigint not null references public.events(id) on delete cascade,
  member_type_id bigint not null references public.member_types(id) on delete cascade,
  primary key (event_id, member_type_id)
);

create table public.attendance (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  member_id bigint not null references public.members(id),
  status text not null default 'present' check (status in ('present', 'cancelled')),
  checked_in_at timestamptz not null default now(),
  checked_in_by uuid not null default auth.uid(),
  unique (event_id, member_id)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  action text not null check (action in ('insert', 'update', 'delete', 'restore')),
  changed_by uuid not null default auth.uid(),
  changed_at timestamptz not null default now(),
  old_data jsonb,
  new_data jsonb
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin' and is_active); $$;

alter table public.profiles enable row level security;
alter table public.member_types enable row level security;
alter table public.members enable row level security;
alter table public.member_field_definitions enable row level security;
alter table public.member_field_values enable row level security;
alter table public.events enable row level security;
alter table public.event_member_types enable row level security;
alter table public.attendance enable row level security;
alter table public.audit_logs enable row level security;

create policy profiles_admin_only on public.profiles for all using (public.is_admin()) with check (public.is_admin());
create policy member_types_admin_only on public.member_types for all using (public.is_admin()) with check (public.is_admin());
create policy members_admin_only on public.members for all using (public.is_admin()) with check (public.is_admin());
create policy member_fields_admin_only on public.member_field_definitions for all using (public.is_admin()) with check (public.is_admin());
create policy member_values_admin_only on public.member_field_values for all using (public.is_admin()) with check (public.is_admin());
create policy events_admin_only on public.events for all using (public.is_admin()) with check (public.is_admin());
create policy event_types_admin_only on public.event_member_types for all using (public.is_admin()) with check (public.is_admin());
create policy attendance_admin_only on public.attendance for all using (public.is_admin()) with check (public.is_admin());
create policy audit_read_admin_only on public.audit_logs for select using (public.is_admin());
